services:
  jellytube:
    image: mralexandersaavedra/jellytube:latest
    container_name: jellytube
    env_file:
      - .env
    volumes:
      - ./output:/app/output
    restart: unless-stopped
    depends_on:
      - invidious
    networks:
      - jellytube_net

  invidious:
    image: quay.io/invidious/invidious:latest
    container_name: invidious
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      INVIDIOUS_CONFIG: |
        db:
          dbname: invidious
          user: invidious
          password: secure_password_saavedra
          host: postgres
          port: 5432
        check_tables: true
        external_port: 3000
        domain: localhost:3000
        https_only: false
        statistics_enabled: false
    depends_on:
      - postgres
    networks:
      - jellytube_net

  postgres:
    image: postgres:17-alpine
    container_name: invidious-db
    restart: unless-stopped
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=invidious
      - POSTGRES_USER=invidious
      - POSTGRES_PASSWORD=secure_password_saavedra
    networks:
      - jellytube_net

networks:
  jellytube_net:
    driver: bridge
