services:
  jellytube:
    build:
      context: ./packages/app
      dockerfile: Dockerfile
    container_name: jellytube
    env_file:
      - .env
    volumes:
      - ./output:/app/output
    restart: unless-stopped
    depends_on:
      - jellytube-proxy

  jellytube-proxy:
    build:
      context: ./packages/proxy
      dockerfile: Dockerfile
    container_name: jellytube-proxy
    restart: unless-stopped
    ports:
      - "9000:3000"
    networks:
      - jellytube_net

networks:
  jellytube_net:
    driver: bridge
