services:
  jellytube:
    build: .
    container_name: jellytube
    env_file:
      - .env
    volumes:
      - ./output:/app/output
    restart: unless-stopped
    depends_on:
      - jellytube-proxy
    networks:
      - jellytube_net

  jellytube-proxy:
    build: ./proxy
    container_name: jellytube-proxy
    restart: unless-stopped
    ports:
      - "9000:3000"
    networks:
      - jellytube_net

networks:
  jellytube_net:
    driver: bridge
