services:
  jellytube:
    image: mralexandersaavedra/jellytube:latest
    container_name: jellytube
    env_file:
      - .env
    volumes:
      - ./output:/app/output
    restart: unless-stopped
    depends_on:
      - piped
    networks:
      - jellytube_net

  piped:
    image: 1337kavin/piped:latest
    container_name: piped
    restart: unless-stopped
    ports:
      - "8081:8080"
    volumes:
      - ./config.properties:/app/config.properties
      - ./config.json:/app/config.json
    environment:
      - PORT=8080
      - HTTP_WORKERS=2
      - PROXY_PART=http://piped-proxy:8080
      - COMPROMISED_PASSWORD_CHECK=true
      - DISABLE_REGISTRATION=false
      - FEED_RETENTION=30
      - MATRIX_SERVER=
      - MATRIX_TOKEN=
      - CAPTCHA_BASE_URL=https://api.capmonster.cloud
      - CAPTCHA_API_KEY=
    depends_on:
      - postgres
      - piped-proxy
    networks:
      - jellytube_net

  piped-proxy:
    image: 1337kavin/piped-proxy:latest
    container_name: piped-proxy
    restart: unless-stopped
    environment:
      - UDS=1
    # No ports needed if only communicated internally via docker network
    networks:
      - jellytube_net

  postgres:
    image: postgres:17-alpine
    container_name: piped-db
    restart: unless-stopped
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=piped
      - POSTGRES_USER=piped
      - POSTGRES_PASSWORD=secure_password_saavedra
    networks:
      - jellytube_net

networks:
  jellytube_net:
    driver: bridge
