services:
  jellytube:
    image: mralexandersaavedra/jellytube:latest
    container_name: jellytube
    env_file:
      - .env
    volumes:
      - ./output:/app/output
    restart: unless-stopped
    depends_on:
      - piped

  piped:
    image: 1337kavin/piped:latest
    container_name: piped
    restart: unless-stopped
    ports:
      - "8081:8080"
    volumes:
      - ./config.properties:/app/config.properties
    depends_on:
      - postgres
      - piped-proxy

  piped-proxy:
    image: 1337kavin/piped-proxy:latest
    container_name: piped-proxy
    restart: unless-stopped
    environment:
      - UDS=1
    # No ports needed if only communicated internally via docker network

  postgres:
    image: postgres:17-alpine
    container_name: piped-db
    restart: unless-stopped
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=piped
      - POSTGRES_USER=piped
      - POSTGRES_PASSWORD=secure_password_saavedra
